baseurl = "https://wesgraba.com"
DefaultContentLanguage = "en"
title = "Wesley Graba"
theme = "beautifulhugo"

enableEmoji = true
enableGitInfo = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "An Engineer with a focus in Systems and Embedded who enjoys working on interdisciplinary problems in a diverse environment."
  mainSections = ["post","posts"]
  logo = "img/wesgraba_headshot.jpg" # Expecting square dimensions
  favicon = "img/favicon.png"
  dateFormat = "2006-01-02"
  commit = false
  rss = false
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Wesley Graba"
  website = "https://wesgraba.com"
  #email = "youremail@domain.com"
  #facebook = "username"
  github = "wgraba"
  gitlab = "wgraba"
  #bitbucket = "username"
  twitter = "wesgraba"
  #reddit = "username"
  linkedin = "wesley-graba"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  mastodon = "https://fosstodon.org/@wesgraba"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"
  #discord = "invite code (https://discord.gg/XXXXXXX)"
  #strava = "userid"

#[[menu.main]]
#    identifier = "about"
#    name = "About"
#    weight = 3

[[menu.main]]
#    parent = "about"
    name = "Résumé"
    url = "https://rxresu.me/wesley.graba/base"
    weight = 2

[[menu.main]]
#    parent = "about"
    name = "About Me"
    url = "page/about/"
    weight = 3

