services:
  vale:
    image: jdkato/vale:latest
    user: ${UID}:${GID}
    volumes:
      - .:/working
    working_dir: /working

  hugo:
    build: .
    user: ${UID}:${GID}
    volumes:
      - .:/working
    working_dir: /working
    ports:
      - "1313:1313"
